### PR TITLE
greeting

### PR DESCRIPTION
**Pull request by NaolAklilu**
Check you name?

### CODE REVIEW

**Comment by Fasilbm** [comment]
Change my name to fasil

**Comment by NaolAklilu** [comment]
Oh Sorry!
Fasil Beyene Right?

**Comment by Fasilbm** [comment]
Yes that is right

**Comment by NaolAklilu** [comment]
Hi Fasil, Can you check the file now.

**Review by Fasilbm — APPROVED** [review]

**Pull request merged**
